spring:
  datasource:
    url: ENC(oSIHPgU87XpyjFABkV3kq6ktPuHPJ1gm1IuispuHExfWUSM5PLVI7mdQ+AqCXQPNfR+FoXhFCUGLbXf5SCuXnMGumRMKNrFyzGnkdCXR45f964G/o0S52ImOIzCU84t+K/JpKlBQDMjOQFFhjlH0zgcLMgfFMO1E)
    username: ENC(PnT/hiHbkm4WchFLBrtSgg==)
    password: ENC(nUVtr4xHB+3X9b1Ks2VuvQ==)
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: ENC(o3Fkyizz0O3JI+AydrMsaIIib/gcQjXP) # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

logging:
  path: /var/logs #配置日志生成路径